name: anchor-ci
description: This is an action to automate building and testing Anchor(Solana) programs
author: Tanmay Munjal

on:
  workflow_call:
    inputs:
      solana_cli_version:
        required: false
        type: string
        default: 1.14.20
      node_version:
        required: false
        type: string
        default: 17.0.1
      anchor_version:
        required: false
        type: string
        default: 0.28.0
      python_version:
        required: false
        type: string
        default: 3.10.6
      solana_rpc:
        required: false
        type: string
        default: localhost
      test_timeout:
        required: false
        type: string
        default: 180
env:
  SOLANA_CLI_VERSION: ${{ inputs.solana_cli_version }}
  NODE_VERSION: ${{ inputs.node_version }}
  ANCHOR_VERSION: ${{ inputs.anchor_version }}
  SOLANA_RPC: ${{ inputs.solana_rpc }}
  PYTHON_VERSION: ${{ inputs.python_version }}
  TEST_TIMEOUT: ${{ inputs.test_timeout }}
  CARGO_CACHE_PATH: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    ./target/

jobs:
  test-formatting:
    name: Testing formatting of contracts and test suite
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.TEST_TIMEOUT }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/setup/
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: cargo fmt -- --check
      - run: npm i prettier
      - run: npm run lint 

  test-contracts:
    name: Test contracts
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.TEST_TIMEOUT }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/setup/
      - uses: ./actions/setup-solana/
      - uses: ./actions/setup-ts/
      - uses: ./actions/setup-amman/
      - uses: ./actions/setup-anchor/
      - run: anchor build --arch sbf 
      - run: anchor deploy
      - run: anchor keys sync
      - run: anchor build --arch sbf
      - run: anchor deploy
      - run: anchor test --arch sbf --skip-local-validator  --skip-deploy --skip-build
      - uses: ./actions/parse-program-compute/