name: "Setup ts"
description: "Setup ts"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: actions/cache@v3
      name: Cache Typescript node_modules
      id: cache-typescript-node-modules
      with:
        path: |
          ./node_modules/
        key: solana-${{ runner.os }}-v0000-${{ env.NODE_VERSION }}-${{ hashFiles('./yarn.lock') }}
    - run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      shell: bash
    - run: yarn
      shell: bash

