name: "Setup Python Program Compute check"
description: "Tests and outputs program compute on each instruction"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }} 
    - name: Decodes program compute logs
      run: python parse_program_compute.py
      shell: bash
