name: "Setups up gcc compiler"
description: "Setups up gcc compiler"
runs:
  using: "composite"
  steps:
      - run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
        shell: bash